services:
  web:
    build:
      context: .
    container_name: SG-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - SG-network

  celery:
    build:
      context: .
    container_name: SG-celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - postgres
    networks:
      - SG-network

  redis:
    image: redis:7
    container_name: SG-redis
    ports:
      - "6379:6379"
    networks:
      - SG-network

  postgres:
    image: postgres:14
    container_name: SG-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - SG-network

networks:
  SG-network:

volumes:
  postgres_data:
