services:
  web:
    build:
      context: .
    container_name: SG-backend
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --log-level debug --proxy-headers
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - SG-network
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  celery:
    build:
      context: .
    container_name: SG-celery
    command: celery -A config worker --loglevel=info
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "celery -A config inspect ping -d celery@$$HOSTNAME | grep -q 'pong' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - postgres
    networks:
      - SG-network

  celery_beat:
    build:
      context: .
    container_name: SG-celery-beat
    command: celery -A config beat --loglevel=info
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'celery beat' > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - postgres
    networks:
      - SG-network

  redis:
    image: redis:7
    container_name: SG-redis
    ports:
      - "6379:6379"
    networks:
      - SG-network

  postgres:
    image: postgres:14
    container_name: SG-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - SG-network

  nginx:
    image: fholzer/nginx-brotli:latest
    container_name: SG-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot:/var/www/certbot
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /root/unity_build:/var/www/unity
    depends_on:
      - web
    networks:
      - SG-network

  # userbot:
  #   build:
  #     context: ./userbot
  #   container_name: SG-userbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./userbot/session:/app/session
  #     # 💡 ИЗМЕНЕНИЕ: Добавляем общую media-папку
  #     - ./media:/app/media
  #   environment:
  #     - API_ID=${API_ID}
  #     - API_HASH=${API_HASH}
  #     - PHONE_NUMBER=${PHONE_NUMBER}
  #     - LOGIN_CODE=${LOGIN_CODE}
  #     - API_BASE_URL=${API_BASE_URL:-http://web:8000}
  #     - API_TOKEN=${API_TOKEN}
  #     - USER_ID=${USER_ID}
  #   networks:
  #     - SG-network


  userbot:
    # Контекст сборки: предполагаем, что Dockerfile, main.py и requirements.txt
    # находятся внутри папки ./userbot
    build:
      context: ./userbot 
      
    container_name: SG-userbot
    restart: unless-stopped
    # Маппинг портов: 8080 - это порт, на котором слушает Uvicorn (FastAPI) внутри контейнера
    ports:
      - "8080:8080"
    volumes:
      # Хранение сессии Pyrogram. Файл сессии будет создан внутри этой папки.
      - ./session:/app/session
      # Общая папка для медиа, как вы просили
      - ./media:/app/media
      
    # Переменные окружения для Pyrogram (API_ID, API_HASH) и FastAPI (API_TOKEN)
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER} # Нужен Pyrogram для первого входа
      - LOGIN_CODE=${LOGIN_CODE}     # Нужен для первого входа, если Pyrogram не может запросить интерактивно
      - API_BASE_URL=${API_BASE_URL:-http://userbot:8080} # Изменено на userbot:8080, так как это имя сервиса
      - API_TOKEN=${API_TOKEN}
      - USER_ID=${USER_ID}
      
    networks:
      - SG-network

networks:
  SG-network:
    driver: bridge

volumes:
  postgres_data: