# Generated by Django 5.2.5 on 2025-08-21 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_nft_id', models.CharField(max_length=255, unique=True, verbose_name='Уникальный ID подарка из ТГ')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(verbose_name='Ссылка на изображение')),
                ('price_ton', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена в TON')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, verbose_name='Редкость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
