# Generated by Django 5.2.5 on 2025-08-28 13:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='backdrop',
            field=models.URLField(blank=True, null=True, verbose_name='Фон (backdrop)'),
        ),
        migrations.AddField(
            model_name='gift',
            name='decimals',
            field=models.PositiveIntegerField(blank=True, default=9, null=True, verbose_name='Десятичные разряды токена'),
        ),
        migrations.AddField(
            model_name='gift',
            name='is_onchain',
            field=models.BooleanField(default=False, verbose_name='Есть ли в блокчейне (onchain)'),
        ),
        migrations.AddField(
            model_name='gift',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель (визуальный тип подарка)'),
        ),
        migrations.AddField(
            model_name='gift',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug подарка'),
        ),
        migrations.AddField(
            model_name='gift',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Символ токена (например GFT или TGIFT)'),
        ),
        migrations.AddField(
            model_name='gift',
            name='ton_contract_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TON-адрес смарт-контракта'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price_ton',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Цена в TON'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, null=True, verbose_name='Редкость'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tg_nft_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Уникальный ID подарка из ТГ'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
