# Generated by Django 5.2.5 on 2025-08-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0003_gift_backdrop_gift_decimals_gift_is_onchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRaffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('active', 'Активен'), ('finished', 'Завершён')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время старта')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles', to='gifts.gift', verbose_name='Приз')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle_wins', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRaffleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='raffle.dailyraffle', verbose_name='Розыгрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'unique_together': {('raffle', 'user')},
            },
        ),
    ]
