# Generated by Django 5.2.5 on 2025-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('bet', 'Ставка'), ('win', 'Выигрыш'), ('purchase', 'Покупка подарка'), ('commission', 'Комиссия'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('TON', 'TON'), ('Stars', 'Stars')], default='TON', max_length=10, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
