# Generated by Django 5.2.5 on 2025-08-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('TON', 'TON'), ('USDT', 'USDT-TON'), ('Stars', 'Stars')], default='TON', max_length=10, verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='TONTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True, verbose_name='Хеш транзакции')),
                ('amount', models.DecimalField(decimal_places=9, max_digits=18, verbose_name='Сумма')),
                ('token', models.CharField(choices=[('TON', 'TON'), ('USDT', 'USDT-TON')], default='TON', max_length=10, verbose_name='Токен')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('sender_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес отправителя')),
                ('block_time', models.DateTimeField(blank=True, null=True, verbose_name='Время блока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'TON Транзакция',
                'verbose_name_plural': 'TON Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='ton_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_transactions', to='transactions.tontransaction', verbose_name='TON транзакция'),
        ),
        migrations.CreateModel(
            name='TONWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес кошелька')),
                ('subwallet_id', models.IntegerField(verbose_name='ID субкошелька')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ton_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'TON Кошелек',
                'verbose_name_plural': 'TON Кошельки',
            },
        ),
        migrations.AddField(
            model_name='tontransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.tonwallet', verbose_name='Кошелек'),
        ),
    ]
