"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import redis



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
STAR_TOKEN =os.getenv('STAR_TOKEN')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "212.8.228.78",
    "127.0.0.1",
    "localhost",
    "teststudiaorbita.ru",
    "web"
]

CSRF_TRUSTED_ORIGINS = [
    "https://teststudiaorbita.ru",
    "https://www.teststudiaorbita.ru",  # если есть www
]

 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'channels',
    "drf_spectacular",
    "drf_spectacular_sidecar",

    'user',
    'games',
    'spin',
    'core',
    'gifts',
    'transactions',
    'raffle'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': int(os.getenv('DB_PORT', 5432)),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "user.User"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# S3 Configuration (для продакшена)
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # AWS S3 Configuration
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'media'
    AWS_DEFAULT_ACL = 'public-read'
    
    # S3 Static settings
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # S3 Media settings
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # URL для медиа файлов
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#env
BOT_TOKEN = os.getenv('BOT_TOKEN')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET')

# JWT конфиг
JWT_SECRET = os.getenv("JWT_SECRET")
JWT_SECRET_2 = os.getenv("JWT_SECRET_2")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
JWT_ACCESS_LIFETIME = timedelta(seconds=int(os.getenv("JWT_ACCESS_LIFETIME", 300)))
JWT_REFRESH_LIFETIME = timedelta(seconds=int(os.getenv("JWT_REFRESH_LIFETIME", 604800)))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "user.authentication.JWTAuthentication",  # наш класс
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # глобально разрешаем
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
}


#django channels
ASGI_APPLICATION = "config.asgi.application"

REDIS_HOST = os.getenv("REDIS_HOST", "redis")  # 'redis' — имя контейнера в docker-compose
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

# Django Channels конфигурация
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Общий клиент Redis (можно импортировать где угодно)
REDIS_CLIENT = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=True)


# Брокер сообщений (Redis)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/1")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")

# Формат времени
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


#swagger 
SPECTACULAR_SETTINGS = {
    "TITLE": "Spinzy Gift API",
    "DESCRIPTION": "Документация для API игры Spinzy Gift",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # чтобы схема не дублировалась в /docs
}

APPEND_SLASH = True

# TON API настройки
TON_API_BASE_URL = "https://toncenter.com/api/v2"
TON_MASTER_WALLET = "UQDPdsD2e_j6T-CAFNCmcC8fJvQixciaaUgJdK8Xz23taTCV"
USDT_CONTRACT_ADDRESS = "EQB-MPwrd1G6WKNkLz_VnVnY_M9ZR5o0vqa5T8l4bFJXwnaA"

# Celery Beat расписание для TON транзакций
CELERY_BEAT_SCHEDULE = {
    'check-ton-transactions': {
        'task': 'transactions.tasks.check_ton_transactions',
        'schedule': 60.0,  # каждые 60 секунд
    },
    'update-wallet-balances': {
        'task': 'transactions.tasks.update_wallet_balances',
        'schedule': 300.0,  # каждые 5 минут
    },
    'cleanup-old-transactions': {
        'task': 'transactions.tasks.cleanup_old_transactions',
        'schedule': 86400.0,  # раз в день
    },
    'process-daily-raffle': {
        'task': 'raffle.tasks.process_daily_raffle',
        'schedule': 60.0,  # раз в сутки
    },
}

# Аватарка по умолчанию для пользователей
DEFAULT_AVATAR_URL = "https://teststudiaorbita.ru/media/avatars/diamond.png"

# Базовый URL сайта для генерации полных ссылок
SITE_URL = os.getenv('SITE_URL', 'https://teststudiaorbita.ru')

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Логирование
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'games.services.auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'games.consumers': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'games.services.game': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'user.services': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'user.services.avatar_service': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'user.services.telegram_auth': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}