# Generated by Django 5.2.5 on 2025-08-21 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pvp', 'PVP рулетка'), ('spin', 'Рекламный спин'), ('daily', 'Ежедневный розыгрыш')], default='pvp', max_length=20, verbose_name='Режим')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('running', 'В процессе'), ('finished', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('pot_amount_ton', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма в TON')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash игры')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=4, verbose_name='Комиссия в %')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_ton', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ставка в TON напрямую')),
                ('total_bet_ton', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итоговая ставка в TON')),
                ('chance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Шанс победы')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_stars', models.PositiveIntegerField(default=0, verbose_name='Ставка в Stars')),
                ('bet_ton', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ставка в TON')),
                ('win_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Выигрыш в TON')),
                ('result_sector', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Выигрышный сектор')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра Spin',
                'verbose_name_plural': 'Игры Spin',
            },
        ),
        migrations.CreateModel(
            name='SpinWheelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Номер сектора')),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Вероятность выпадения')),
            ],
            options={
                'verbose_name': 'Сектор колеса',
                'verbose_name_plural': 'Сектора колеса',
                'ordering': ['index'],
            },
        ),
    ]
