# Generated by Django 5.2.5 on 2025-08-17 11:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_type', models.CharField(default='default', max_length=50, verbose_name='Тип спина')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Номер сектора')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Рекламный сектор')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Вес выпадения')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.gift', verbose_name='Привязанный подарок')),
            ],
            options={
                'verbose_name': 'Сектор спина',
                'verbose_name_plural': 'Сектора спина',
                'unique_together': {('spin_type', 'index')},
            },
        ),
    ]
