# Generated by Django 5.2.5 on 2025-08-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('gifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='gifts.gift', verbose_name='Подарки в ставке'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='spingame',
            name='gift_won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.gift', verbose_name='Выигранный подарок'),
        ),
        migrations.AddField(
            model_name='spingame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='spinwheelsector',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.gift', verbose_name='Привязанный подарок'),
        ),
        migrations.AlterUniqueTogether(
            name='spinwheelsector',
            unique_together={('index',)},
        ),
    ]
