# Generated by Django 5.2.5 on 2025-08-17 19:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_spinsector'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spingame',
            options={'verbose_name': 'Игра Spin', 'verbose_name_plural': 'Игры Spin'},
        ),
        migrations.RemoveField(
            model_name='spingame',
            name='sectors_count',
        ),
        migrations.AddField(
            model_name='spingame',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Выигрыш в TON'),
        ),
        migrations.CreateModel(
            name='SpinWheelSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Номер сектора')),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5, verbose_name='Вероятность выпадения')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.gift', verbose_name='Привязанный подарок')),
            ],
            options={
                'verbose_name': 'Сектор колеса',
                'verbose_name_plural': 'Сектора колеса',
                'ordering': ['index'],
                'unique_together': {('index',)},
            },
        ),
        migrations.DeleteModel(
            name='SpinSector',
        ),
    ]
